version: "3"
services:
  frontend_flask:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dockerfile
    container_name: frontend_flask
    ports:
      - 5001:5001
      - 8011:8011


  backend_flask:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dockerfile
    container_name: backend_flask
    ports:
      - 5000:5000
      - 8010:8010

  node_exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
        - 9100:9100
    pid: host
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
        - 9090:9090
    volumes:
        - "./prometheus.yml:/etc/prometheus/prometheus.yml"
        - "./rules.yml:/etc/prometheus/rules.yml"
    restart: always

  grafana:
    image: grafana/grafana:8.2.5
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
